---
# Secret — Superset admin credentials (REPLACE before applying)
# kubectl create secret generic superset-secret \
#   --namespace analytics \
#   --from-literal=SUPERSET_ADMIN_USERNAME=admin \
#   --from-literal=SUPERSET_ADMIN_PASSWORD=<strong-password> \
#   --from-literal=SUPERSET_ADMIN_EMAIL=admin@bookstore.local \
#   --from-literal=SUPERSET_SECRET_KEY=<random-32-char-string> \
#   --from-literal=ANALYTICS_DB_URL=postgresql+psycopg2://analyticsuser:password@analytics-db.analytics.svc.cluster.local:5432/analyticsdb
apiVersion: v1
kind: Secret
metadata:
  name: superset-secret
  namespace: analytics
type: Opaque
data:
  SUPERSET_ADMIN_USERNAME: YWRtaW4=
  SUPERSET_ADMIN_PASSWORD: Q0hBTkdFX01F
  SUPERSET_ADMIN_EMAIL: YWRtaW5AYm9va3N0b3JlLmxvY2Fs
  SUPERSET_SECRET_KEY: Q0hBTkdFX01FX1JBTkRPTV8zMl9DSEFSUw==
  ANALYTICS_DB_URL: cG9zdGdyZXNxbCtwc3ljb3BnMjovL2FuYWx5dGljc3VzZXI6Q0hBTkdFX01FQGFuYWx5dGljcy1kYi5hbmFseXRpY3Muc3ZjLmNsdXN0ZXIubG9jYWw6NTQzMi9hbmFseXRpY3NkYg==

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: superset-pvc
  namespace: analytics
spec:
  storageClassName: local-hostpath
  volumeName: superset-pv
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset
  namespace: analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superset
  template:
    metadata:
      labels:
        app: superset
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      initContainers:
        - name: superset-init
          image: apache/superset:latest
          command:
            - sh
            - -c
            - |
              # Install psycopg2-binary for PostgreSQL connectivity
              uv pip install psycopg2-binary --target /extra-packages --quiet && \
              export PYTHONPATH=/extra-packages:$PYTHONPATH && \
              superset db upgrade && \
              superset fab create-admin \
                --username $SUPERSET_ADMIN_USERNAME \
                --firstname Store \
                --lastname Admin \
                --email $SUPERSET_ADMIN_EMAIL \
                --password $SUPERSET_ADMIN_PASSWORD || true && \
              superset init
          envFrom:
            - secretRef:
                name: superset-secret
          env:
            - name: SUPERSET_CONFIG_PATH
              value: /app/pythonpath/superset_config.py
          volumeMounts:
            - name: superset-config
              mountPath: /app/pythonpath
            - name: data
              mountPath: /app/superset_home
            - name: extra-packages
              mountPath: /extra-packages
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
      containers:
        - name: superset
          image: apache/superset:latest
          command: ["gunicorn", "--bind", "0.0.0.0:8088", "--workers", "2", "superset.app:create_app()"]
          ports:
            - containerPort: 8088
          envFrom:
            - secretRef:
                name: superset-secret
          env:
            - name: SUPERSET_CONFIG_PATH
              value: /app/pythonpath/superset_config.py
            - name: PYTHONPATH
              value: "/extra-packages"
          volumeMounts:
            - name: superset-config
              mountPath: /app/pythonpath
            - name: data
              mountPath: /app/superset_home
            - name: extra-packages
              mountPath: /extra-packages
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /health
              port: 8088
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
      volumes:
        - name: superset-config
          configMap:
            name: superset-config
        - name: data
          persistentVolumeClaim:
            claimName: superset-pvc
        - name: extra-packages
          emptyDir: {}

---
# ConfigMap — minimal Superset config
apiVersion: v1
kind: ConfigMap
metadata:
  name: superset-config
  namespace: analytics
data:
  superset_config.py: |
    import os
    SECRET_KEY = os.environ["SUPERSET_SECRET_KEY"]
    SQLALCHEMY_DATABASE_URI = "sqlite:////app/superset_home/superset.db"
    WTF_CSRF_ENABLED = True
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SECURE = False   # Set True when TLS is enabled
    FEATURE_FLAGS = {"ENABLE_TEMPLATE_PROCESSING": True}

---
# NodePort service — accessible at host port 32000
apiVersion: v1
kind: Service
metadata:
  name: superset
  namespace: analytics
spec:
  selector:
    app: superset
  ports:
    - port: 8088
      targetPort: 8088
      nodePort: 32000
  type: NodePort
