---
# ecom-service AuthorizationPolicy — L4-only (no waypoint proxy in Ambient mode).
# Spring Security handles JWT validation and path-level authorization at L7.
# Istio ztunnel enforces namespace-level access at L4.
# NOTE: The Istio gateway pod runs in the 'infra' namespace (gatewayClassName: istio
# with Gateway resource in infra ns), so external user traffic originates from infra.
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: ecom-service-policy
  namespace: ecom
spec:
  selector:
    matchLabels:
      app: ecom-service
  rules:
    # Allow traffic from the Istio gateway (external user/UI requests routed through gateway)
    - from:
        - source:
            namespaces: ["infra"]
    # Allow ui-service nginx proxy calls (ui-service is in ecom namespace, proxies /ecom/* here)
    - from:
        - source:
            namespaces: ["ecom"]
    # Allow Prometheus scraping from observability namespace
    - from:
        - source:
            namespaces: ["observability"]
