---
# Analytics CDC Consumer — reads Debezium CDC topics and writes to analytics DB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-consumer
  namespace: analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-consumer
  template:
    metadata:
      labels:
        app: analytics-consumer
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: analytics-consumer
          image: bookstore/analytics-consumer:latest
          imagePullPolicy: Never
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka.infra.svc.cluster.local:9092"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: analytics-db-secret
                  key: DATABASE_URL
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
