---
# Exposes Kiali on NodePort 32100.
# Accessible at http://localhost:32100/kiali via kind's extraPortMappings
# (containerPort: 32100 / hostPort: 32100 in infra/kind/cluster.yaml).
# No proxy container needed — kind's own host port binding handles this.
apiVersion: v1
kind: Service
metadata:
  name: kiali-nodeport
  namespace: istio-system
  labels:
    app: kiali
    component: nodeport-access
spec:
  type: NodePort
  selector:
    app: kiali
  ports:
    - name: http-kiali
      port: 20001
      targetPort: 20001
      nodePort: 32100
      protocol: TCP
